### PR TITLE
Backdrop with highlighting

### PR DESCRIPTION
**Pull request by hakimio**
Implemented basic backdrop with active element highlighting in TourMatMenuModule like discussed in [#125](https://github.com/isaacplmann/ngx-tour/issues/125).

### CODE REVIEW

**Comment by isaacplmann** [comment]
I like the idea of using a box-shadow, but you don't need to add a new element and service to make that work.

Just add this to your css:

```
.touranchor--is-active {
    position: relative;
    box-shadow: 0 0 0 9999px rgba(0,0,0,0.7);
}
```

**Comment by isaacplmann** [comment]
That also has the added benefit of handling rounded borders better and scrolling works correctly.

**Comment by isaacplmann** [comment]
Hm, actually you'd need your div solution if the active item was inside an overflow hidden element.

**Comment by isaacplmann** [comment]
Before I merge this, it needs to be off by default and have some way to turn it on.  The way that makes the most sense to me is to add a `showBackdrop` property to the `IStepOption` interface and then check that value each time a new step is shown.

**Comment by hakimio** [comment]
Your "touranchor--is-active" CSS class solution doesn't work in all cases.

I haven't seen any issues with scrolling in Angular Material app which uses [Sidenav](https://material.angular.io/components/sidenav/overview) for layout and navigation.

I can make it off by default and I can add a new property to IStepOption, but that would require creating new interface which extends IStepOption (INgxmStepOption?) because IStepOption is declared in core module. Is that ok?

**Comment by hakimio** [comment]
@isaacplmann I've made the change you requested. Let me know if there is something else I should change.

**Comment by isaacplmann** [comment]
Looking good from my quick skim read.  I'll work on testing and merging later today.

**Comment by isaacplmann** [comment]
Thanks!  I appreciate the feature PR.

**Comment by isaacplmann** [comment]
Good catch.  It looks like my first demo deploy failed.  It should be updating now.

**Comment by themaawaa** [comment]
.touranchor--is-active styling does work for me.

**Comment by hakimio** [comment]
@themaawaa So? How is that relevant to this PR?

**Pull request merged**
