### PR TITLE
update to rxjs 6 and ng6

### PR DESCRIPTION
**Pull request by LPCmedia**

### CODE REVIEW

**Comment by isaacplmann** [comment]
@LPCmedia thanks! I'll merge this today or tomorrow.

**Comment by LPCmedia** [comment]
There seems to be a console log error on the material example. 
not sure about that but point me in the right direction.

**Comment by bluefire2121** [comment]
This branch looks good. I didn't know about the `rxjs/observable/merge` library @LPCmedia,  but great find. [https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md]

**Comment by isaacplmann** [comment]
Looking into this PR today.  The build process seems to be broken for the `npm start` command.  I think I'll rework the whole build process to use angular cli to make future maintenance simpler.

**Comment by isaacplmann** [comment]
I have `ngx-tour-core` building with the new setup, but I'm getting stuck on compiling any of the plugins that depend on it.

**Comment by isaacplmann** [comment]
When I get a chance to come back to this, I'll try resorting to `npm link`ing the `ngx-tour-core` library and building the rest normally.

**Comment by LPCmedia** [comment]
Let me know what it should be doing.

**Pull request merged**
