### PR TITLE
Support for ngx-bootstrap

### PR DESCRIPTION
**Pull request by kahboom**
Add support for [ngx-bootstrap](https://github.com/valor-software/ngx-bootstrap).This needs some changes prior to merging, as it is not building properly (due to the new ngx-tour-ngx-bootstrap plugin, which was published on npm [here](https://www.npmjs.com/package/ngx-tour-ngx-bootstrap)).

On `npm install` from the root directory, the `ngx-tour-ngx-bootstrap` package does not look like the other plugin packages, presumably because it is not built beforehand. When running `npm run pub` I get the follow error, related to the new plugin: https://gist.github.com/kahboom/9033e175df187400005cce3ea5b48d4d

Mostly:
```
BUILD ERROR
'queue' is not exported by node_modules/rxjs/scheduler/queue.js
Error: 'queue' is not exported by node_modules/rxjs/scheduler/queue.js
```

Will do some additional research, but wanted to create the PR to see if anything obvious stood out.

cc @isaacplmann . Also, let me know if you'd like for me to squash commits into a single commit.

re #47

### CODE REVIEW

**Comment by kahboom** [comment]
@isaacplmann Any ideas?

**Comment by isaacplmann** [comment]
Thanks for the reminder. I'll look at this today.

**Comment by kahboom** [comment]
screenshot 2017-09-19 15 28 10
screenshot 2017-09-19 15 29 10

And on creating the `dest/ngx-tour-ngx-bootstrap` dir manually in case of permission issues (guessing because of the ENOENT I was getting earlier): https://gist.github.com/kahboom/b5ff90a28354c173f11bec66ba6d1983

I wonder, are you manually building the plugins and publishing them after they've been built? If so, it could help to decouple them and have them as separate npm modules with separate GH repos.

**Comment by kahboom** [comment]
Sorry for the hassle @isaacplmann , we might be using ngx-tour in Red Hat but our project currently uses ngx-bootstrap. I have to have it working by this Friday for a technical preview and would really like to stick with it.

**Comment by isaacplmann** [comment]
Yep, I'm wrapping a ticket and then I'll work on your PR.

**Comment by isaacplmann** [comment]
I've gotten past a couple errors:
1. EACCESS error was stopping me from running `npm link` because my global node_modules folder was not writeable.
2. `Error: 'queue' is not exported by node_modules/rxjs/scheduler/queue.js` solved by adding this line to `ng-package-ngx-bootstrap.json`:
```
"rxjs/scheduler/queue": "Rx.Observable.prototype",
```

This gets me through `npm run build:lib:all`.
I'm working on a third error after running `npm start`
3. `NgxBootstrapModule is not an NgModule`

I'll update as I go.

**Comment by isaacplmann** [comment]
I also had to lock down typescript to 2.2.2 and rxjs to 5.4.0.

The 3rd error was resolved by adding a missing `x` to line 28 of `ngx-bootstrap.module.ts`
```ts
export class NgxBootstrapModule { }
```

I can run the demo now and I see a popup for ngx-bootstrap.  I can use the arrows to move between steps, but there are no buttons on the popup.  Want to take it from here?

I need to work on another issue where steps that span routes aren't working in the demo any more.

**Comment by isaacplmann** [comment]
Let me know if that unblocks you.

**Comment by isaacplmann** [comment]
How is this going?  Are you still stuck?

**Comment by kahboom** [comment]
@isaacplmann - Yes, still stuck. What are the steps for contributing? I'd assume:

1. From plugin dir, after writing necessary code in both the project root dir and new plugin dir, install deps with `npm install` from the plugin dir
2. Build with `ng build`.
3. Publish to npm.
4. Push to GH repo (my fork)
5. Go back to the root dir and installing deps which pull in the published plugin.
6. Pull in my fork changes from the project using it.

Probably run `npm link` at some point as well. In other words, everything should be done within the plugin directory, or `./ngx-tour-ngx-bootstrap`. It looks like I can't build the project until the plugin gets bundled into `./dist/ngx-tour-ngx-bootstrap`.

Everything that gets built from the project root dir does not get checked in, as far as I can see, so I shouldn't need to do anything from the root dir unless I want to run the server locally. Please tell me if I'm missing anything.

Here I am trying out a few random things:

```
» ngx-tour-ngx-bootstrap $ npm install
npm WARN ngx-tour-ngx-bootstrap@1.0.3 requires a peer of ngx-bootstrap@1.9.1 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of @angular/common@^4.2.5 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of @angular/core@^4.2.5 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of @angular/router@^4.2.5 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of core-js@^2.4.1 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of rxjs@^5.4.2 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of zone.js@^0.8.12 but none was installed.

up to date in 0.357s

» ngx-tour-ngx-bootstrap $ npm link
npm WARN ngx-tour-ngx-bootstrap@1.0.3 requires a peer of ngx-bootstrap@1.9.1 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of @angular/common@^4.2.5 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of @angular/core@^4.2.5 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of @angular/router@^4.2.5 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of core-js@^2.4.1 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of rxjs@^5.4.2 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of zone.js@^0.8.12 but none was installed.

up to date in 0.065s
/usr/local/lib/node_modules/ngx-tour-ngx-bootstrap -> /Users/kahboom/Projects/ngx-tour/ngx-tour-ngx-bootstrap

» ngx-tour-ngx-bootstrap $ cd .. && npm install
npm ERR! code ENOLOCAL
npm ERR! Could not install from "dist/ngx-tour-ngx-bootstrap" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kahboom/.npm/_logs/2017-09-20T13_23_12_967Z-debug.log

» ngx-tour $ npm link
npm ERR! code ENOLOCAL
npm ERR! Could not install from "dist/ngx-tour-ngx-bootstrap" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kahboom/.npm/_logs/2017-09-20T13_23_16_681Z-debug.log

» ngx-tour $ cd ngx-tour-ngx-bootstrap/

» ngx-tour-ngx-bootstrap $ npm link
npm WARN ngx-tour-ngx-bootstrap@1.0.3 requires a peer of ngx-bootstrap@1.9.1 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of @angular/common@^4.2.5 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of @angular/core@^4.2.5 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of @angular/router@^4.2.5 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of core-js@^2.4.1 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of rxjs@^5.4.2 but none was installed.
npm WARN ngx-tour-core@1.0.3 requires a peer of zone.js@^0.8.12 but none was installed.

up to date in 0.067s
/usr/local/lib/node_modules/ngx-tour-ngx-bootstrap -> /Users/kahboom/Projects/ngx-tour/ngx-tour-ngx-bootstrap
```

What am I missing?

**Comment by isaacplmann** [comment]
It sounds like you're doing more work than you need to.  Here are the steps that I do when I'm developing the library.  All from the root directory:

1. `npm run build:lib:all` (or `npm run build:lib:ngx-bootstrap` if that's the only thing you changed)
2. `npm start` to start the demo app and verify your plugin

Once you're satisfied that it is working correctly in the demo, I can merge the code in and then I'll do step 3.

3. `npm run pub:lib:ngx-bootstrap`.

Or secret option 3b is you could create and maintain your own github repo and npm library that just depends on `ngx-tour-core`.

On a side note, I think you're right that it would probably be good to split these projects into separate github repos at some point - it gets difficult to figure out which package someone is filing an issue about.

**Comment by kahboom** [comment]
@isaacplmann - Thanks for the quick response; I knew I was doing more than should be required but was trying to figure out what I was missing :joy:. Okay, so I appreciate the instructions but can't try them because I get an error of `ng-packagr command not found` likely because I have not run `npm install`. I can't run `npm install` anymore after pulling in the latest changes because I get the following:

```
» ngx-tour $ npm install
npm ERR! code ENOLOCAL
npm ERR! Could not install from "dist/ngx-tour-ngx-bootstrap" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kahboom/.npm/_logs/2017-09-20T13_59_30_491Z-debug.log
```

I ran `rm -rf node_modules` from the root dir and plugin dir just in case, but yep.

**Comment by isaacplmann** [comment]
I'm looking into it.

**Comment by isaacplmann** [comment]
I updated the root `package.json` with this line:

```
"ngx-tour-ngx-bootstrap": "^1.0.0",
```

Then:

1. `npm install`
2. `npm run build:lib:all`
3. `npm start`

Sorry I missed that.

**Comment by isaacplmann** [comment]
Hm.  It looks like it is pulling `ngx-tour-ngx-bootstrap` from the npm registry and not updating with local changes when I run `npm run build:lib:ngx-bootstrap`.  Still investigating...

**Comment by isaacplmann** [comment]
Nevermind, it is updating correctly.  I was just editing the `ng-bootstrap` plugin instead of the `ngx-bootstrap` plugin.

**Comment by isaacplmann** [comment]
Any time you edit the actual plugin you'll need to run `npm run build:lib:ngx-bootstrap`.  The demo app's `ng serve` won't automatically build it for you.

**Comment by kahboom** [comment]
Thanks @isaacplmann , I figured it wouldn't build automatically but wasn't sure if I needed to do something within the plugin dir itself. It builds properly now, thank you! I'm testing some things with the docs and then will resolve conflicts, hopefully it will be good to go today.

For some reason, in the demo I don't see a Prev or Next button for ngx-bootstrap. Looking into it.

**Comment by isaacplmann** [comment]
I saw the missing Prev and Next buttons as well.  I think it's something about the way you're hooking up to the ngx-bootstrap popover directive.

**Comment by isaacplmann** [comment]
Let me know if you need more help with this.  I know you wanted to have it finished by today.

**Comment by kahboom** [comment]
Thank you @isaacplmann , really appreciate it. Will try to check on the Prev/Next buttons if I get a chance, juggling several things at once for the project so I hope to get around to it so that we can then get the PR merged in (once you're okay with it obviously). :) Thanks for all of your help. 👍

**Comment by kahboom** [comment]
@isaacplmann - Apologies for the delay and for leaving this PR just sitting here; I got busy but now need to finish this up this week (am very behind). Everything looks okay except for some quirks with how ngx-bootstrap works and what methods it offers. 

The first problem is that the popover appears in the wrong place. The second thing is that the content is not passed through to the step, so naturally, there is no `currentStep` or previous or next step. For instance, I can't pass content to `.open()` how you would be able to with ng-boostrap's `.show({{ content }})`. I've opened an issue for this here: https://github.com/valor-software/ngx-bootstrap/issues/2853

The `tour-anchor.directive.ts` `showTourStep` method looks like this:

```
  public showTourStep(step: IStepOption): void {
    console.log('this.tourStepTemplate.template: ' + this.tourStepTemplate.template);
    this.popover = this.tourStepTemplate.template;
    this.popoverTitle = step.title;
    this.container =  'body';
    switch (step.placement) {
      case 'above':
        this.placement = 'top';
        break;
      case 'below':
        this.placement = 'bottom';
        break;
      case 'right':
      case 'after':
        this.placement = 'right';
        break;
      case 'left':
      case 'before':
        this.placement = 'left';
        break;
      default:
        this.placement = 'top';
    }
    //this.show({ step }); // This is not accepted by ngx-bootstrap
    this.show();
    if (!step.preventScrolling) {
      if (!withinviewport(this.element.nativeElement, { sides: 'bottom' })) {
        (<HTMLElement>this.element.nativeElement).scrollIntoView(false);
      } else if (!withinviewport(this.element.nativeElement, { sides: 'left top right' })) {
        (<HTMLElement>this.element.nativeElement).scrollIntoView(true);
      }
    }
  }
```

Which results, not surprisingly, in a browser console warning about there not being a `currentStep`:

screenshot 2017-10-17 09 29 12

As you can see, the popover is appended to the NgxBootstrap menu item. And if I click the menu item again, then it appends it to the correct area:

screenshot 2017-10-17 09 29 27

If I use a `popoverContext` method provided by ngx-bootstrap that _does_ accept a parameter, it seems there _is_ a `currentStep`, as the warning goes away, but the End button no longer appears and obviously no content appears. I'm not entirely sure how to use this method so I'll do some poking around later today.

Here is what that results in:

screenshot 2017-10-17 09 35 04

screenshot 2017-10-17 09 36 54

If you have any suggestions, I'd greatly appreciate it!

**Comment by isaacplmann** [comment]
FWIW, I had to submit a pull request to `ng-bootstrap` for them to provide the ability to supply context to a popover.

However, I think `ngx-bootstrap` already has the ability [built in](https://valor-software.com/ngx-bootstrap/#/popover#api-reference).  Try this:

```ts
this.popover = this.tourStepTemplate.template;
...
this.popoverContext = { step };
this.show();
```

I'm not sure why the placement is wrong.  I'd start investigating the css.

**Comment by kahboom** [comment]
@isaacplmann - Is there any way I can apply a class like this? I know we discussed this in this issue, but adding a class to the template doesn't work. The issue is specific to my plugin and ngx-bootstrap (for instance, the positioning and the arrow) so I'd like to have a class just for that plugin.

screenshot 2017-10-17 15 12 24

**Comment by isaacplmann** [comment]
That's something you'd set in the ngx-bootstrap code.  In the tourAnchorDirective you can set `this.containerClass = 'ngx-bootstrap'`.

**Comment by kahboom** [comment]
That's right, had an airhead moment there. ;D

**Comment by isaacplmann** [comment]
It looks like you're getting close.  Let me know when you're ready for me to see if its ready to be merged.

**Comment by kahboom** [comment]
@isaacplmann - Thanks! Apologies for the hideous commit history. I can clean this up later today if you'd like.

So, it's functional and looks fine now, enough so that I think this can be merged in if you are happy with it, but there are three things I've observed, for which I think separate PRs could be opened:

1. `position: 'bottom'` is still not supported, for some reason, despite the fact that you've updated the typings to allow `any`. It seems like it only recognizes 'below', as ng-bootstrap uses, so it defaults it to 'top' or 'above' when you try to use 'below'. This is illustrated with the second step in the demo.
2. When the demo page is first loaded, there is unusual behavior with the placement of _only the first_ popover step:
   - It does not append the popover to the right place. It appends to the top menu button. This only happens on page load, perhaps when referencing `ngx-bootstrap.module#NgxBootstrapModule` in `app.module.ts`.
   - The curious thing is that if you pressed 'Next', that popover is in the right location.
   - Even curiouser is that if you press 'Previous' from there, back to the first step, it places it in the right place.
   - I think this behavior could be the result of the first item on this list.
3. The buttons where the first step should be (e.g. 'Start Demo Tour') are picking up some strange styling that darken it and make them smaller. I've checked and am using the same CSS classes. It must be something related to ngx-bootstrap, though the buttons shouldn't look like that with those classes anyway: https://valor-software.com/ngx-bootstrap/index-bs4.html#/buttons

On page load, popover positioning is wrong and appends in the wrong place, and the buttons pick up strange styling:

screenshot 2017-10-20 10 17 05

Next step:

screenshot 2017-10-20 10 17 11

Previous step, back to first:

screenshot 2017-10-20 10 17 17

The steps:

screenshot 2017-10-20 10 30 48


Thanks again! Let me know if you have any thoughts/ideas on the points I mentioned.

**Comment by isaacplmann** [comment]
Thanks for your work. I've pulled in your changes and I'll make those last little edits before publishing.

**Comment by isaacplmann** [comment]
Thanks!  Merged. To publish this I'll need you to add me as an owner to the `ngx-tour-ngx-bootstrap` package on npm.

```
npm owner add isaacplmann ngx-tour-ngx-bootstrap
```

**Comment by kahboom** [comment]
Thanks @isaacplmann - Done. I also added you to the npm package for `ngx-tour`. A while back I unintentionally published the main package to npm when I was testing things out. I was surprised to see it had not been published to npm yet, and it automatically made me the owner:

- ngx-tour-ngx-bootstrap: https://www.npmjs.com/package/ngx-tour-ngx-bootstrap
- ngx-tour: https://www.npmjs.com/package/ngx-tour

Feel free to close out this issue whenever you think is appropriate. Thanks again for all of your help! Greatly appreciate it.

**Comment by kahboom** [comment]
I wonder why the demo page hasn't picked up the changes yet? Perhaps needs to be built manually.

**Comment by isaacplmann** [comment]
I never published the demo because I couldn't publish the library.  That will be remedied soon.

**Comment by isaacplmann** [comment]
`ngx-tour-ngx-bootstrap` has been published.  The demo has been updated and will be visible whenever github's cache expires.

**Comment by kahboom** [comment]
Thanks!

**Pull request merged**
