### PR TITLE
The library now depends on Angular 7. Fixes #136.

### LINKED ISSUE #136: Extend peer dependencies to Angular 7
**Issue description**

running `npm install` throws the following warning:

```
npm WARN ngx-tour-core@3.0.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-tour-core@3.0.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-tour-core@3.0.0 requires a peer of @angular/router@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-tour-ngx-bootstrap@3.0.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-tour-ngx-bootstrap@3.0.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
```
**Steps to reproduce and a minimal demo of the problem**

`npm install` with Angular 7

**Current behavior**

`npm install` shows a couple of warning due to peer dependencies.

**Expected/desired behavior**

No warnings should be shown

### PR DESCRIPTION
**Pull request by hakimio**
Bumped Angular version to 7, updated some other dependencies. All libraries and the demo app builds and runs successfully.

### CODE REVIEW

**Comment by hakimio** [comment]
Should we update "ngx-popper" as well?

**Comment by isaacplmann** [comment]
Thanks for the PR!  I'll review this today.

**Comment by isaacplmann** [comment]
Didn't get to this today.  I'll look at this first thing tomorrow.

**Comment by hakimio** [comment]
@isaacplmann I might have forgotten to bump version number in package.json not only for popper but also for "ngx-tour-ngx-bootstrap".

**Comment by isaacplmann** [comment]
I caught the popper version, but I missed ngx-tour-ngx-bootstrap.  I’m publishing that now.

**Comment by isaacplmann** [comment]
ngx-tour-ngx-bootstrap@4.0.0 is now published

**Comment by hakimio** [comment]
@isaacplmann The demo app seems to be broken. Did you build it with "--prod" flag?
```
ng build --prod
```

**Comment by isaacplmann** [comment]
Good catch.  It worked from `ng serve` so I thought it was good to go.  I've updated the build script to include `--prod`.

**Pull request merged**
