### PR TITLE
Popper defaults

### PR DESCRIPTION
**Pull request by damo1884**
Disable click outside popup to close by default since it does not trigger the tourService.end$ event

### CODE REVIEW

**Comment by damo1884** [comment]
Looks like this overlaps with the other PR here: https://github.com/isaacplmann/ngx-tour/pull/89

Is this because my fork is now ahead by 1 PR?

**Comment by isaacplmann** [comment]
That could be.  I sent you an invitation last week to become a collaborator on this repo.  If you accept that invitation, you'll be able to merge these PRs yourself.  Or just make commits directly.

**Comment by isaacplmann** [comment]
Is this a bugfix PR?  Or a new feature PR?  Should the new version for ngx-tour-ngx-popper be 2.0.1 or 2.1.0?

**Comment by damo1884** [comment]
Just accepted the invitation now thanks had not seen the mail sorry.

In order for these changes to get picked up by ngx-tour-ngx-popper npm package it would need a version update and be published again. This fixes an issue when setting the popperSettings via the tour json

**Pull request merged**
