### PR TITLE
Allow multiple 'undefined' tourAnchors #168

### PR DESCRIPTION
**Pull request by Kyle-Dornblaser**

### CODE REVIEW

**Comment by hakimio** [comment]
@isaacplmann Can you merge this?

**Comment by hakimio** [comment]
@isaacplmann any particular reason you don't want to merge this?

**Comment by hakimio** [comment]
@isaacplmann can you also release a new minor version?

**Comment by isaacplmann** [comment]
Done.

**Comment by hakimio** [comment]
@isaacplmann 
Thank you very much :)

**Pull request merged**
