### PR TITLE
Advanced ng bootstrap placement

### PR DESCRIPTION
**Pull request by pzero24**
NG Bootstrap has support for advanced placements, for example left-below. I went ahead and added that support to the IStepOption and the tour anchor directive.

### CODE REVIEW

**Comment by isaacplmann** [comment]
Here is a link to the [placement options](https://ng-bootstrap.github.io/#/components/popover/api#NgbPopover).  This is editing the `ngx-tour-core` package which  the `ngx-tour-md-menu` library depends on as well.  Unfortunately, the `placement` option is not common to both libraries.  I agree that I shouldn't be limiting the options that the underlying UI library provides.  What if we removed the `switch` statement completely and just did this:

```ts
this.placement = step.placement || 'top';
```

That way if new placements get added to the underlying library, the tour code doesn't need to change.  The only thing you lose with that is the typing support for the `placement` property.  That could be solved by overwriting the `IStepOptions` in `ngx-tour-ng-bootstrap` and `ngx-tour-md-menu` to have values that are appropriate for those libraries.

If you don't have any other ideas, this is how I'd recommend modifying the PR.

1. Reduce the `placement` logic to the one liner above.
2. Extend the type definition for `IStepOption` in `ngx-tour-ng-bootstrap` to be exactly the values that `ng-bootstrap` expects, even importing `PlacementArray` from `ng-bootstrap` directly.
3. Update the documentation to mimic the `ng-bootstrap` documentation (i.e. copy/paste their documentation) and provide a link to [the page you copied from](https://ng-bootstrap.github.io/#/components/popover/api#NgbPopover)

What do you think?

**Comment by pzero24** [comment]
I think that is a great idea. I will make those changes later today.

**Comment by pzero24** [comment]
In order to override the IStepOption in the library implementations, I had to make the TourService accept a generic type that extends IStepOption, with each library implementation providing a concrete implementation of TourService. For instance, this is the three concrete implementations for each library:

```
export class ConsoleTourService extends TourService<IStepOption> {}
export class MdMenuTourService extends TourService<IStepOption> {}
export class NgbTourService extends TourService<INgbStepOption> {}
```

Then in the respective public_api.d.ts files, I export those classes, but renamed as TourService:

```
export { MdMenuTourService as TourService } in './md-menu-tour.service'
```

I also export the core TourService as CoreTourService to prevent duplicate exports.

**Comment by isaacplmann** [comment]
I committed a change to your PR that used a default value for the generic:

```ts
TourService<T extends IStepOptions = IStepOptions>
```

This lets us leave the console and md-menu libraries untouched while keeping the autocomplete for ng-bootstrap.  I'm just waiting for github to notice the new commit and update the PR.

**Comment by isaacplmann** [comment]
Thanks for your contribution!

**Comment by pzero24** [comment]
I did not update the version number, which I am not sure if you did either. That might cause people's installation to break due to the breaking change of removing above and below.

**Comment by isaacplmann** [comment]
PRs don't generally update the version number.  I'll take care of that
before I publish a newer version to npm.

**Comment by isaacplmann** [comment]
New version is out with this functionality 2.0.0-beta.5-1

**Pull request merged**
