### PR TITLE
ngx-popper support

### PR DESCRIPTION
**Pull request by damo1884**
Add support for [ngx-popper](https://github.com/MrFrankel/ngx-popper)

No need for a bloated UI-Framework to get this into your project

### CODE REVIEW

**Comment by isaacplmann** [comment]
Thanks for the contribution!  I'm running your PR now.

**Comment by isaacplmann** [comment]
I switched the `stepTemplate` from a `PopperContent` to a `TemplateRef`.

I also removed your use of `[innerHtml]` because that opens up a security hole.  If you're pulling in your tour steps from the server somehow, that could be intercepted and people can inject whatever they want into your app.

The way to allow html in the content is to set to a type of `string | TemplateRef` and then people can use a `TemplateRef` to put html or components or anything they want there.

**Comment by isaacplmann** [comment]
The `string | TemplateRef` feature is discussed in issue #72 .  I'd like to add that at some point - or you could add it as a separate PR.

**Comment by damo1884** [comment]
Awesome yes the stepTemplate was not working for me to override it.

I can add the [innerHTML] in my custom template then.

Also is the location of the css styles ok?

**Comment by damo1884** [comment]
Also I am wondering if I should expose all the possible settings from ngx-popper to the step template?

image

This would enable full control of ngx-popper from the steps definition

And ignore any settings not present

**Comment by isaacplmann** [comment]
I don't see the css styles you added.  Where are they?

Yes, you can expose the popper settings, but I would wrap them all up in one popperSettings property.

**Comment by isaacplmann** [comment]
Make sure to update the documentation so that people know they can add that.

Would you like to become a maintainer for this repo?  That way you can make changes to the `ngx-popper` code (and other plugins too) as you see fit.

**Comment by damo1884** [comment]
The styles are in styles.css

I wasn't sure where best to put them.

It would be great if I could submit some new patches so yes to maintainer

Should I update this PR with the popperSettings ?

**Comment by damo1884** [comment]
Any idea how best to handle these properties?

image

**Comment by isaacplmann** [comment]
Yes, add popperSettings to this PR.

I'm investigating how to ship a separate css file for people to include.

**Comment by isaacplmann** [comment]
It looks like `ng-packagr` doesn't support shipping a separate css file out of the box.  I'll need to add some cross platform `cp` command to the `devDependencies` and add a step to the `build:lib:ngx-popper` script to copy the css file to the `dist` folder.  Then users of the library can manually import the css file if they want to use your default css.

I prefer to make the css optional, because I hate fighting css rules that are baked into UI components.

**Comment by damo1884** [comment]
Without the bare minimum css the popper will have no background and look transparent

**Comment by damo1884** [comment]
popperSettings are added now

**Comment by isaacplmann** [comment]
Ok. Merging.  I'll publish it under ngx-tour-ngx-popper and then give you publish rights to that package.

**Comment by damo1884** [comment]
When I add `"ngx-tour-ngx-popper": "^2.0.0"` to my package.json and run `npm install`

I don't get the custom button titles in the IStepOption

image

**Comment by isaacplmann** [comment]
This has been published to npm, but the demo failed to build for some reason.  I need to head out for the weekend - I'll try to get the demo fixed on Monday.

**Comment by damo1884** [comment]
I think ngx-tour-core has not been published yet with custom button titles.

Thanks again for working through this with me.

Have a great weekend :)

**Pull request merged**
